-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New query)
-- It inserts 12 mock projects, skipping any that already exist.

INSERT INTO public."Projects" (id, title, blurb, description, category, date, likes, image, github, makers, tools, status)
VALUES
(
  'glow-garden',
  'Glow Garden',
  'A capacitive plant pot that pulses softly when you touch the soil. Built for the Engineering common room.',
  E'Glow Garden started as a late-night experiment: what if a plant could tell you when it wanted attention? We wired a capacitive touch sensor directly into the soil, so a gentle press on the dirt triggers a slow, breathing pulse through a ring of addressable LEDs embedded in the pot rim.\n\nThe enclosure is 3D-printed in two halves — an inner liner to hold the plant and soil, and an outer shell with a diffusion channel for the LEDs. We painted the outside with a clay-textured spray and the result looks almost natural on a desk until it starts glowing.\n\nThe Arduino Pro Mini sleeps between touch events to keep battery life reasonable. We have the pot running on two AA batteries in the Engineering common room and it\'s been going for three weeks without a change.',
  'Electronics',
  '2026-04-11',
  142,
  NULL,
  'https://github.com',
  ARRAY['Aria T.', 'Theo K.'],
  ARRAY['Soldering iron', '3D printer', 'Arduino'],
  NULL
),
(
  'tessellate',
  'Tessellate',
  'A crochet blanket that maps a Penrose tiling across 280 hand-hooked hexagons. Took most of Semester One.',
  E'Penrose tilings are non-repeating patterns that can cover an infinite plane without ever tiling the same way twice. Tessellate translates one such tiling into a full-size crochet blanket — 280 individual hexagons, hand-hooked and seamed over twelve weeks.\n\nThe colour assignment came from running the tiling algorithm in Python and mapping tile "type" to one of five yarn colours, giving the finished piece a gradient flow that looks almost intentional but follows strict mathematical rules.\n\nEach hexagon took about 25 minutes to hook. The seaming took another three full sessions. The blanket now lives in the club common room.',
  'Textiles',
  '2026-03-02',
  88,
  NULL,
  NULL,
  ARRAY['Mei L.'],
  ARRAY['Crochet hook', 'Wool', 'Python'],
  NULL
),
(
  'bytecake',
  'Bytecake',
  'Pixel-art layer cakes for COMPSCI 230. Each slice is a sprite — and there are two-bit and four-bit cakes.',
  E'This was built for the end-of-semester COMPSCI 230 celebration. The brief was simple: make something edible that teaches binary. The answer was a layer cake where each horizontal layer represents a bit — vanilla for 0, chocolate for 1.\n\nThe two-bit cake is four slices tall (00 through 11). The four-bit cake goes to sixteen layers. Cutting a slice reveals the binary number for that slice position, frosted onto the top in pixel font. We used a piping bag and food colouring to label each slice 0000 through 1111.\n\nIt took two full days of baking and about a kilogram of buttercream. Both cakes were gone in twenty minutes.',
  'Food',
  '2026-05-01',
  311,
  NULL,
  NULL,
  ARRAY['Sam W.', 'Jordan A.'],
  ARRAY['Piping bag', 'Oven', 'Patience'],
  NULL
),
(
  'caster',
  'Caster',
  'An open-source dice tower that rolls a real D20 on a Cherry MX switch. Plug it into anything.',
  E'Caster is a USB HID device that looks like a small dice tower. Press the button — a Cherry MX Blue, because feedback matters — and it rolls a true random D20 and types the result wherever your cursor is. Spreadsheets, character sheets, Discord chat: it works anywhere text input does.\n\nThe internals are a resin-printed shell housing an RP2040 Tiny, a physical D20 tumbler section (purely decorative, purely satisfying), and the switch mounted at the front. True randomness comes from the RP2040\'s hardware RNG peripheral.\n\nThe firmware is open source and ships with profiles for D4, D6, D8, D10, D12, D20 and D100 — hold the button on boot to cycle between them.',
  '3D Print',
  '2026-02-18',
  64,
  NULL,
  'https://github.com',
  ARRAY['Finn O.'],
  ARRAY['Resin printer', 'Soldering iron', 'CircuitPython'],
  NULL
),
(
  'quokka',
  'Quokka Macropad',
  'A nine-key RP2040 macropad for VS Code, built around a hand-routed PCB and a cheery 3D-printed shell.',
  E'Quokka started as a KiCad learning exercise and turned into the most-used thing on Priya''s desk. It''s a 3×3 macropad built on a custom PCB — hand-routed, meaning no auto-router was used, because the trace layout is part of the craft.\n\nThe RP2040 microcontroller runs QMK-compatible firmware written in CircuitPython, with nine keys mapped to the most common VS Code actions: toggle terminal, format document, go to definition, run tests, and five custom layer shortcuts. A rotary encoder was added late in the design for volume and scroll.\n\nThe shell is printed in a warm orange PLA with rounded corners and a slight quokka face embossed on the front. It took three print attempts to get the keycap alignment right.',
  'Electronics',
  '2026-04-26',
  198,
  NULL,
  'https://github.com',
  ARRAY['Priya R.'],
  ARRAY['KiCad', 'Soldering iron', '3D printer', 'CircuitPython'],
  NULL
),
(
  'forager',
  'Forager',
  'A Swift app that IDs mushrooms growing on campus after the rain. Trained on a tiny CoreML dataset we labelled ourselves.',
  E'After a rainy week in March, the engineering courtyard filled with at least six different species of fungi. Forager was built to answer the obvious question: which ones are edible?\n\nThe app uses a CoreML model trained on a dataset of ~1,400 labelled photos taken on campus and from public domain collections. Point your phone at a mushroom, get a species name, a confidence score, and a clear EDIBLE / AVOID indicator. The model runs entirely on-device — no network needed.\n\nTraining and labelling was done collaboratively across a weekend. The model currently identifies 22 species with 84% top-1 accuracy on the test split. A Figma-designed UI wraps it with a field-guide aesthetic.',
  'Code',
  '2026-03-19',
  124,
  NULL,
  'https://github.com',
  ARRAY['Liam B.', 'Naia P.'],
  ARRAY['Swift', 'CoreML', 'Figma', 'Python'],
  NULL
),
(
  'stickmaker',
  'Stickmaker',
  'A generative sticker pack — you tap once and get a unique vinyl sticker printed at our cutter. Ran every Tuesday this semester.',
  E'Stickmaker is a p5.js sketch running on a touchscreen kiosk in the common room. Tap the screen, get a unique sticker design generated from a set of parametric shapes, colour palettes and layering rules. The design gets sent directly to our vinyl cutter via a simple Node.js bridge and the sticker is weeded and ready in about ninety seconds.\n\nThe generative system uses about 200 lines of p5.js. There are twelve shape primitives, eight palettes and four layout modes — the combinations mean no two stickers are identical. Over a semester, we''ve cut more than 400 unique designs.\n\nThe kiosk is built on a repurposed iPad in a 3D-printed stand. Emi designed the brand typography and the UX.',
  'Art',
  '2026-04-04',
  76,
  NULL,
  NULL,
  ARRAY['Emi H.'],
  ARRAY['Procreate', 'Vinyl cutter', 'p5.js', 'Node.js'],
  NULL
),
(
  'kowhai-lamp',
  'Kōwhai Lamp',
  'A laser-cut plywood lamp inspired by kōwhai flowers. Three nested shades, warm-white LED, ten dollars in materials.',
  E'The kōwhai (Sophora microphylla) has one of the most recognisable silhouettes in Aotearoa — long compound leaves and clusters of tubular yellow flowers. This lamp takes that silhouette and turns it into a parametric laser-cut shade.\n\nThree layers of 3mm birch ply are cut with progressively more open patterns — the innermost layer is near-solid for diffusion, the outer two cast detailed shadows on the wall. All three slot together with friction-fit tabs and no glue on the shade itself.\n\nThe base is a simple hardwood block with a warm-white LED module pressed in. Total material cost: around $10 NZD from the university workshop offcuts. Assembly time: about an hour.',
  'Wood',
  '2026-01-30',
  102,
  NULL,
  NULL,
  ARRAY['Tane M.'],
  ARRAY['Laser cutter', 'Wood glue', 'Inkscape'],
  NULL
),
(
  'yarnscape',
  'Yarnscape',
  'A woven wall hanging mapping the route between our common room and the Engineering library. Every member walked it and logged time.',
  E'Yarnscape is a data-driven textile. Every member of the club walked the same route — common room to Engineering library — and logged how long it took them. That time data was then translated into a woven pattern: fast walkers got tight, high-contrast warps; slower walkers got looser, gradient-heavy sections.\n\nThe final piece is about 80cm × 120cm, woven on a frame loom using a mix of wool and cotton yarn. The time data is embedded in the structure of the weave itself — you can''t read the numbers, but you can feel the difference in texture.\n\nRu designed the mapping algorithm in a spreadsheet and wove the whole thing over six weeks.',
  'Textiles',
  '2025-12-12',
  41,
  NULL,
  NULL,
  ARRAY['Ru S.'],
  ARRAY['Loom', 'Wool', 'GPS log', 'Spreadsheet'],
  NULL
),
(
  'open-hours',
  'Open Hours, Term 1',
  'Twelve weeks of Tuesday drop-in soldering, sewing and snacks. Sixty-four people, four broken irons, zero serious burns.',
  E'Open Hours is the heartbeat of the club — every Tuesday from 6 to 9pm, the common room is open for anyone to come and make things. No agenda, no registration, no experience required.\n\nTerm 1 2026 ran for twelve weeks and saw 64 individual members pass through. Projects completed included the Glow Garden, three custom keyboards, a crocheted mushroom colony, a batch of resin earrings, and one very ambitious attempt at a mechanical automaton (ongoing).\n\nFour soldering irons were broken (one memorably), approximately 40 bags of chips were consumed, and zero people got seriously hurt. We consider this a success.',
  'Workshops',
  '2026-04-29',
  215,
  NULL,
  NULL,
  ARRAY['The Make Crew'],
  ARRAY['Soldering iron', 'Snacks', 'Enthusiasm'],
  NULL
),
(
  'loaf-lab',
  'Loaf Lab',
  'A sourdough fermentation logger — temperature, humidity, rise — plotted live to a Notion page. The starter is named Glenn.',
  E'Glenn is a sourdough starter that has been alive since March 2025. Loaf Lab is the monitoring system Tas built to keep Glenn alive and understand why some bakes fail.\n\nAn Arduino Nano reads a DHT22 temperature/humidity sensor and an ultrasonic distance sensor (for measuring starter rise) every five minutes and pushes data to a Google Sheet via a Python bridge script. A Notion integration pulls from the sheet and displays a live chart with annotations for each feed and bake.\n\nThe surprising finding: the common room air conditioning dropping below 18°C overnight is the single biggest predictor of a flat loaf. Glenn now has a small insulated box.',
  'Food',
  '2026-03-28',
  167,
  NULL,
  'https://github.com',
  ARRAY['Tas R.'],
  ARRAY['Arduino', 'Notion API', 'Python', 'Oven'],
  NULL
),
(
  'polywall',
  'Polywall',
  'Modular climbing holds for the new boulder wall behind the workshop. Twenty-two FDM prints, epoxied to plywood. They hold.',
  E'The workshop has had a half-built bouldering wall for two years. Polywall finished it. The project involved designing twenty-two parametric climbing holds in Fusion 360 — jugs, crimps, slopers and a couple of novelty shapes (a spanner, a fist) — printing them in 40% infill PETG, and sanding them to a rough grip texture.\n\nEach hold is bolted through the plywood with a T-nut insert and coated with a sand-epoxy mix for texture. The design files are on GitHub — the parametric system means you can resize any hold to easy, medium or hard difficulty just by changing one variable.\n\nAfter three months of regular use, all twenty-two holds are still attached. We''re calling that a structural success.',
  '3D Print',
  '2026-02-09',
  53,
  NULL,
  'https://github.com',
  ARRAY['Jess Y.', 'Kai N.'],
  ARRAY['3D printer', 'Fusion 360', 'Epoxy', 'Sandpaper'],
  NULL
)
ON CONFLICT (id) DO NOTHING;
